"""add active_po_id to users

Revision ID: 46761b244215
Revises: b2da621fb9d7
Create Date: 2026-08-14 22:47:46.592496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46761b244215'
down_revision: Union[str, None] = 'b2da621fb9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_po_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'purchase_orders', ['active_po_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_po_id')
    # ### end Alembic commands ###
