"""add purchase_requisitions table

Revision ID: 867264878a80
Revises: e5a22b445975
Create Date: 2026-08-15 11:22:00.351142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '867264878a80'
down_revision: Union[str, None] = 'e5a22b445975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_requisitions',
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('deadline', sa.String(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_requisitions')
    # ### end Alembic commands ###
