"""add created_at to purchase_orders

Revision ID: b2da621fb9d7
Revises: b612744a4bd6
Create Date: 2026-08-14 12:36:24.815542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b2da621fb9d7'
down_revision: Union[str, None] = 'b612744a4bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'created_at')
    # ### end Alembic commands ###
