"""add po_id to requisition_sessions

Revision ID: b612744a4bd6
Revises: fac70719a199
Create Date: 2026-08-13 22:37:14.114899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b612744a4bd6'
down_revision: Union[str, None] = 'fac70719a199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisition_sessions', sa.Column('po_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'requisition_sessions', 'purchase_orders', ['po_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requisition_sessions', type_='foreignkey')
    op.drop_column('requisition_sessions', 'po_id')
    # ### end Alembic commands ###
